/**
 * Seed Nest 10 (Example)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ResponseBody { 
    statusCode: number;
    message: ResponseBody.MessageEnum;
    data: object;
}
export namespace ResponseBody {
    export type MessageEnum = 'success';
    export const MessageEnum = {
        Success: 'success' as MessageEnum
    };
}


