/**
 * Seed Nest 10 (Example)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDemoDto { 
    email: string;
    password: string;
    roles: Array<CreateDemoDto.RolesEnum>;
    isEnabled?: boolean;
}
export namespace CreateDemoDto {
    export type RolesEnum = 'Admin' | 'Moderator' | 'User';
    export const RolesEnum = {
        Admin: 'Admin' as RolesEnum,
        Moderator: 'Moderator' as RolesEnum,
        User: 'User' as RolesEnum
    };
}


