/**
 * Seed Nest 10 (Example)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreateUserDto } from '../model/models';
import { UserLoginDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    infoAdmin(extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     */
    infoUser(extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param userLoginDto 
     */
    login(userLoginDto: UserLoginDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    logout(extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @param createUserDto 
     */
    register(createUserDto: CreateUserDto, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     */
    rotateToken(extraHttpRequestParams?: any): Observable<string>;

}
