/**
 * Seed Nest 10 (Example)
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface UploadServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    findAllDocument(extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     */
    findAllFile(extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     */
    findAllImage(extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param id 
     */
    findOneDocument(id: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param id 
     */
    findOneFile(id: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param id 
     */
    findOneImage(id: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param id 
     */
    removeDocument(id: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param id 
     */
    removeFile(id: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param id 
     */
    removeImage(id: string, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param file 
     */
    uploadDocument(file?: Blob, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param file 
     */
    uploadFile(file?: Blob, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param file 
     */
    uploadImage(file?: Blob, extraHttpRequestParams?: any): Observable<object>;

}
